### ISSUE TITLE
Change formatting of OSC message

### ISSUE THREAD

**Issue by KonVas** [dirkleas/tsharky#1]
Is it possible to change the format of the OSC message the moment is created from python osc lib? For example, it would be really helpful if there were breakpoints between the key and value pairs so the OSC receiver on the other side would have an easier task to parse it.

**Comment by dirkleas** [comment]
you could definitely reformat the raw messages coming from tshark prior to forwarding them through OSC -- tell me a bit about what you'd like to see/do and I can provide more detail/sample code

**Comment by KonVas** [comment]
> tell me a bit about what you'd like to see/do and I can provide more detail/sample code

Thanks, I think, it will be easier for me to receive the data as an array in this form: `key, value` to appear separated by a comma instead of = sign. For example,
`[ack, 1, tsval, 2, foo, 3, fooBar, 4]` etc. 

This will make its easier for me to parse it further. Hope that's not a big bother... thanks.

**Comment by dirkleas** [comment]
paste a copy of a couple of records/lines of the raw data you're looking at and I'll provide a snippet of code to convert it to this friendlier format

**Comment by KonVas** [comment]
So I have this raw incoming OSC: `[ /tsharky, 673 116.224482 192.168.1.101 → 52.27.151.4  TCP 66 54059 → 443 [ACK] Seq=1 Ack=32 Win=2047 Len=0 TSval=1041718843 TSecr=2855541598 ]`

I would like to have it in this format, if possible: `["Seq", "Ack", "win", "Len", "TSval", "TSecr",  32, 2047, 0, 1041718843, 2855541598]`

So all keys are listed first and then the values respectively in the same order of the keys. Obviously, the ip addresses and other information are not carrying any values I could use, so maybe the message can be divided in two parts `[ [], [] ]` for example so the first could be the array with keys and values.

**Comment by dirkleas** [comment]
given you specific requirement, you could do something like:
 
```
x = '[ /tsharky, 673 116.224482 192.168.1.101 → 52.27.151.4 TCP 66 54059 → 443 [ACK] Seq=1 Ack=32 Win=2047 Len=0 TSval=1041718843 TSecr=2855541598 ]'
x = list(map(lambda y: y.split('='), x.split()[13:-1]))
print( list(map(lambda y: y[0], x)) + list(map(lambda y: y[1], x)))
```

of course, there are lots of ways to do this -- regular expressions would also be a fun exercise ;-)

**Comment by KonVas** [comment]
Hi thanks for the immediate response. I tried to combine the above in this file https://github.com/dirkleas/tsharky/blob/master/tsharky.py -but no luck, I am not very experienced in Python. Is it possible to merge it with the code in the file? I am going to use in SuperCollider btw assigning keys and values in a dictionary, I can upload the SC file in your repo for others, when I am done thanks.

**Comment by dirkleas** [comment]
in that case, instead of sending everything, just send the data -- you'll need to add it to the osc messages for each of your parsed data fields as follows in your updated gist code:

```
traffic = list(map(lambda y: y.split('='), traffic.split()[13:-1]))
for v in map(lambda y: y[1], traffic): msg.add_arg(v, 'i')
```

no need to send the field labels over osc to supercollider -- just remember the order of the fields so you know what's what

**Comment by KonVas** [comment]
Hey, thanks for the tip. Hate to bring this up once again, I tried the snippet above but I got some error.

```
import subprocess
from pythonosc import osc_message_builder, udp_client

osc = udp_client.UDPClient('localhost', 57120)
popen = subprocess.Popen(['tshark', '-l'], stdout=subprocess.PIPE)
for traffic in iter(popen.stdout.readline, ''):
    traffic = traffic.decode('utf-8').strip()
    traffic = list(map(lambda y: y.split('='), traffic.split()[13:-1]))
    msg = osc_message_builder.OscMessageBuilder(address='/tsharky')
    for v in map(lambda y: y[1], traffic): msg.add_arg(v, 'i')
    print(traffic)
    msg = msg.build()
    osc.send(msg)

```
>  File "tsharky.py", line 25, in <module>
    msg = msg.build()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pythonosc/osc_message_builder.py", line 166, in build
    raise BuildError('Could not build the message: {}'.format(be))
pythonosc.osc_message_builder.BuildError: Could not build the message: Wrong argument value passed: required argument is not an integer

**Comment by dirkleas** [comment]
`for v in map(lambda y: y[1], traffic): msg.add_arg(int(v), 'i') # convert value to integer`

**Comment by KonVas** [comment]
I am still getting the same error I think.

```
osc = udp_client.UDPClient('localhost', 57120)
popen = subprocess.Popen(['tshark', '-l'], stdout=subprocess.PIPE)
for traffic in iter(popen.stdout.readline, ''):
    traffic = traffic.decode('utf-8').strip()
    traffic = list(map(lambda y: y.split('='), traffic.split()[13:-1]))
    msg = osc_message_builder.OscMessageBuilder(address='/tsharky')
    for v in map(lambda y: y[1], traffic): msg.add_arg(int(v), 'i') # convert value to integer
    print(traffic)
    msg = msg.build()
    osc.send(msg)
```

> Capturing on 'Wi-Fi'
> 5 []
> [['Win', '2047'], ['Len', '0'], ['TSval', '891047190']]
> []
> []
> []
> [['Win', '1050'], ['Len', '0'], ['TSval', '3116974128']]
> 11 Traceback (most recent call last):
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pythonosc/parsing/osc_types.py", line 95, in write_int
>     return struct.pack('>i', val)
> struct.error: 'i' format requires -2147483648 <= number <= 2147483647
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pythonosc/osc_message_builder.py", line 144, in build
>     dgram += osc_types.write_int(value)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pythonosc/parsing/osc_types.py", line 97, in write_int
>     raise BuildError('Wrong argument value passed: {}'.format(e))
> pythonosc.parsing.osc_types.BuildError: Wrong argument value passed: 'i' format requires -2147483648 <= number <= 2147483647
> 
> > During handling of the above exception, another exception occurred:
> > 
> > Traceback (most recent call last):
> >   File "tsharky.py", line 25, in <module>
> >     msg = msg.build()
> >   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pythonosc/osc_message_builder.py", line 166, in build
> >     raise BuildError('Could not build the message: {}'.format(be))
> > pythonosc.osc_message_builder.BuildError: Could not build the message: Wrong argument value passed: 'i' format requires -2147483648 <= number <= 2147483647
> >  /tsharky/ [master*] tshark: An error occurred while printing packets: Broken pipe.

**Comment by dirkleas** [comment]
you can fix this by passing the values through as strings -- alter as follows `for v in map(lambda y: y[1], traffic): msg.add_arg(v, 's')` and convert to appropriate type in supercollider or scale them in python before sending

**Comment by KonVas** [comment]
Hey Dirkleas, I understand this is becoming a little bit to much to ask, but I would be very grateful to make it work, and I am a bit agnostic of python. Now I am getting it working for a little bit around 62 captures but then it crashes again, here is the output: 

> Capturing on 'Wi-Fi'
62 Traceback (most recent call last):
  File "tsharky.py", line 23, in <module>
    for v in map(lambda y: y[1], traffic): msg.add_arg(v, 's')
  File "tsharky.py", line 23, in <lambda>
    for v in map(lambda y: y[1], traffic): msg.add_arg(v, 's')
IndexError: list index out of range
 [master*] tshark: An error occurred while printing packets: Broken pipe.

**Comment by dirkleas** [comment]
what general programming/scripting language are most familiar with?

**Comment by KonVas** [comment]
A little bit of JS, but mostly SuperCollider these days.

**Comment by dirkleas** [comment]
different raw messages are being generated by tshark — you’ll need to ignore them or add support for those other message formats. the easiest approach if you’re merely generating performance fodder for supercollider is to wrap the for-loop content with a try/except like:

```
for traffic in iter(popen.stdout.readline, ''):
    try:
        traffic = traffic.decode('utf-8').strip()
        traffic = list(map(lambda y: y.split('='), traffic.split()[13:-1]))
        msg = osc_message_builder.OscMessageBuilder(address='/tsharky')
        for v in map(lambda y: y[1], traffic): msg.add_arg(v, 's')
        print(traffic)
        msg = msg.build()
        osc.send(msg)
    except: pass
```

perhaps something like [this](https://nodejs.org/api/child_process.html) + [this](
https://github.com/adzialocha/osc-js#readme) would be a better fit given your javascript/node.js experience — the mechanics are very similar to the gist
